In [1]:
from flask import Flask, render_template, url_for, request
import pandas as pd
import numpy as np
import pickle
import sklearn
from math import trunc
import joblib

In [ ]:
app = Flask(__name__)

model = pickle.load(open('predict_blood.pkl', 'rb'))

@app.route('/')
def home():
    return render_template('home.html')

@app.route('/predict', methods=['POST', 'GET'])
def predict():
#     data1 = request.form['Regency']
#     data2 = request.form['Frequency']
#     data3 = request.form['Monetary']
#     data4 = request.form['Time']
#     arr = np.array([[data1, data2, data3, data4]])
    int_features = [int(x) for x in request.form.values()]
    final = [np.array(int_features)]
    print(int_features)
    print(final)
    predictions = model.predict_proba(final)
    print(predictions)
    output = "{:f}".format(predictions[0][1])
    print(output)
    return render_template('predict.html', data=output)
if __name__ == '__main__':
    app.run(debug=True, use_reloader=False)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: on


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [26/Feb/2021 20:15:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2021 20:15:25] "POST /predict HTTP/1.1" 200 -


[2, 50, 12500, 98]
[array([    2,    50, 12500,    98])]
[[1.00000000e+000 1.41526993e-130]]
0.000000


127.0.0.1 - - [26/Feb/2021 20:16:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2021 20:16:10] "POST /predict HTTP/1.1" 200 -


[1, 24, 6000, 77]
[array([   1,   24, 6000,   77])]
[[1.00000000e+00 8.59860303e-60]]
0.000000


127.0.0.1 - - [26/Feb/2021 20:18:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2021 20:18:18] "POST /predict HTTP/1.1" 200 -


[1, 12, 3000, 35]
[array([   1,   12, 3000,   35])]
[[1.00000000e+00 3.55330036e-31]]
0.000000


127.0.0.1 - - [26/Feb/2021 20:18:31] "GET / HTTP/1.1" 200 -
